baseURL = 'https://brainstorm.github.io'
languageCode = 'en-us'
title = 'Brainstorm'
theme = 'archie'
copyright = "© Nelson Rodrigues"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
mode = 'auto'
customcss = ["css/theme.css", "css/tabs.css"]
customJS = ["js/tabs.js"]

[[params.social]]
name = 'Linkedin'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/nelson-rodrigues-847676104'

[[params.social]]
name = 'Github'
icon = 'github'
url = 'https://github.com/nelsonr'

[[params.social]]
name = 'Codepen'
icon = 'codepen'
url = 'https://codepen.io/nelsonr'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'About'
url = '/about'
weight = 2
